export const channels = {
  snapshot: "app:snapshot",
  chooseFiles: "files:choose",
  chooseFolder: "files:choose-folder",
  filePath: "files:path",
  setOutputDirectory: "settings:output-directory",
  chooseTool: "settings:choose-tool",
  addJobs: "jobs:add",
  removeJob: "jobs:remove",
  clearFinished: "jobs:clear-finished",
  startQueue: "jobs:start-queue",
  cancelJob: "jobs:cancel",
  retryJob: "jobs:retry",
  revealOutput: "jobs:reveal-output",
  readLog: "jobs:read-log",
  activate: "license:activate",
  deactivate: "license:deactivate",
  stateChanged: "app:state-changed",
  jobProgress: "jobs:progress",
  keygenChooseKey: "keygen:choose-key",
  keygenGenerate: "keygen:generate",
} as const;
